/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev */

#include "src/decurrent.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ChannelConfig, ChannelConfig, AUTO)


PB_BIND(TriggerChannel, TriggerChannel, AUTO)


PB_BIND(TriggerConfig, TriggerConfig, AUTO)


PB_BIND(WaveConfig, WaveConfig, AUTO)


PB_BIND(DACConfig, DACConfig, AUTO)


PB_BIND(Config, Config, AUTO)


PB_BIND(USBRequest, USBRequest, AUTO)


PB_BIND(AnalogScale, AnalogScale, AUTO)


PB_BIND(USBResponse, USBResponse, AUTO)


PB_BIND(CalibrationValue, CalibrationValue, AUTO)


PB_BIND(AnalogChannelCalibration, AnalogChannelCalibration, AUTO)


PB_BIND(CalibrationInfo, CalibrationInfo, 2)












/* @@protoc_insertion_point(eof) */
